import Head from 'next/head';
import TodoModal from '@/containers/dashboard/id/modals/todoModal/TodoModal';

export default function Home() {
  return (
    <>
      <Head>
        <title>taskify</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.png' />
      </Head>
      <main>
        <TodoModal />
      </main>
    </>
  );
}
