import Head from 'next/head';
import TodoModal from '@/containers/dashboard/id/modals/todoModal/TodoModal';
import TodoEditModal from '@/containers/dashboard/id/modals/todoEditModal/TodoEditModal';
import TodoCreateModal from '@/containers/dashboard/id/modals/todoCreateModal/TodoCreateModal';
export default function Home() {
  return (
    <>
      <Head>
        <title>taskify</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.png' />
      </Head>
      <main>
        <TodoModal />
        <TodoEditModal />
        <TodoCreateModal />
      </main>
    </>
  );
}
